const Ziggy = {
    url: "http://localhost",
    port: null,
    defaults: {},
    routes: {
        "sanctum.csrf-cookie": {
            uri: "sanctum/csrf-cookie",
            methods: ["GET", "HEAD"],
        },
        home: { uri: "/", methods: ["GET", "HEAD"] },
        "public.properties": {
            uri: "browse-properties",
            methods: ["GET", "HEAD"],
        },
        "public.properties.show": {
            uri: "browse-properties/{property}",
            methods: ["GET", "HEAD"],
            parameters: ["property"],
            bindings: { property: "slug" },
        },
        "public.inquiries.store": {
            uri: "browse-properties/{property}/inquire",
            methods: ["POST"],
            parameters: ["property"],
            bindings: { property: "slug" },
        },
        "seller-requests.create": {
            uri: "sell-property",
            methods: ["GET", "HEAD"],
        },
        "seller-requests.store": { uri: "sell-property", methods: ["POST"] },
        "seller-requests.success": {
            uri: "sell-property/success",
            methods: ["GET", "HEAD"],
        },
        register: { uri: "register", methods: ["GET", "HEAD"] },
        login: { uri: "login", methods: ["GET", "HEAD"] },
        dashboard: { uri: "dashboard", methods: ["GET", "HEAD"] },
        "broker.dashboard": {
            uri: "broker/dashboard",
            methods: ["GET", "HEAD"],
        },
        "broker.pending-approval": {
            uri: "broker/pending-approval",
            methods: ["GET", "HEAD"],
        },
        "admin.dashboard": { uri: "admin/dashboard", methods: ["GET", "HEAD"] },
        "admin.brokers.index": {
            uri: "admin/brokers",
            methods: ["GET", "HEAD"],
        },
        "admin.brokers.approve": {
            uri: "admin/brokers/{user}/approve",
            methods: ["POST"],
            parameters: ["user"],
            bindings: { user: "id" },
        },
        "admin.brokers.reject": {
            uri: "admin/brokers/{user}/reject",
            methods: ["DELETE"],
            parameters: ["user"],
            bindings: { user: "id" },
        },
        logout: { uri: "logout", methods: ["POST"] },
        "profile.edit": { uri: "profile", methods: ["GET", "HEAD"] },
        "profile.update": { uri: "profile", methods: ["PATCH"] },
        "profile.destroy": { uri: "profile", methods: ["DELETE"] },
        "properties.index": { uri: "properties", methods: ["GET", "HEAD"] },
        "properties.create": {
            uri: "properties/create",
            methods: ["GET", "HEAD"],
        },
        "properties.store": { uri: "properties", methods: ["POST"] },
        "properties.show": {
            uri: "properties/{property}",
            methods: ["GET", "HEAD"],
            parameters: ["property"],
            bindings: { property: "slug" },
        },
        "properties.edit": {
            uri: "properties/{property}/edit",
            methods: ["GET", "HEAD"],
            parameters: ["property"],
            bindings: { property: "slug" },
        },
        "properties.update": {
            uri: "properties/{property}",
            methods: ["PUT", "PATCH"],
            parameters: ["property"],
            bindings: { property: "slug" },
        },
        "properties.destroy": {
            uri: "properties/{property}",
            methods: ["DELETE"],
            parameters: ["property"],
            bindings: { property: "slug" },
        },
        "properties.toggle-featured": {
            uri: "properties/{property}/toggle-featured",
            methods: ["POST"],
            parameters: ["property"],
            bindings: { property: "slug" },
        },
        "clients.index": { uri: "clients", methods: ["GET", "HEAD"] },
        "clients.create": { uri: "clients/create", methods: ["GET", "HEAD"] },
        "clients.store": { uri: "clients", methods: ["POST"] },
        "clients.show": {
            uri: "clients/{client}",
            methods: ["GET", "HEAD"],
            parameters: ["client"],
            bindings: { client: "id" },
        },
        "clients.edit": {
            uri: "clients/{client}/edit",
            methods: ["GET", "HEAD"],
            parameters: ["client"],
            bindings: { client: "id" },
        },
        "clients.update": {
            uri: "clients/{client}",
            methods: ["PUT", "PATCH"],
            parameters: ["client"],
            bindings: { client: "id" },
        },
        "clients.destroy": {
            uri: "clients/{client}",
            methods: ["DELETE"],
            parameters: ["client"],
            bindings: { client: "id" },
        },
        "inquiries.index": { uri: "inquiries", methods: ["GET", "HEAD"] },
        "inquiries.create": {
            uri: "inquiries/create",
            methods: ["GET", "HEAD"],
        },
        "inquiries.store": { uri: "inquiries", methods: ["POST"] },
        "inquiries.show": {
            uri: "inquiries/{inquiry}",
            methods: ["GET", "HEAD"],
            parameters: ["inquiry"],
            bindings: { inquiry: "id" },
        },
        "inquiries.edit": {
            uri: "inquiries/{inquiry}/edit",
            methods: ["GET", "HEAD"],
            parameters: ["inquiry"],
            bindings: { inquiry: "id" },
        },
        "inquiries.update": {
            uri: "inquiries/{inquiry}",
            methods: ["PUT", "PATCH"],
            parameters: ["inquiry"],
            bindings: { inquiry: "id" },
        },
        "inquiries.destroy": {
            uri: "inquiries/{inquiry}",
            methods: ["DELETE"],
            parameters: ["inquiry"],
            bindings: { inquiry: "id" },
        },
        "inquiries.respond": {
            uri: "inquiries/{inquiry}/respond",
            methods: ["POST"],
            parameters: ["inquiry"],
            bindings: { inquiry: "id" },
        },
        "transactions.index": { uri: "transactions", methods: ["GET", "HEAD"] },
        "transactions.create": {
            uri: "transactions/create",
            methods: ["GET", "HEAD"],
        },
        "transactions.store": { uri: "transactions", methods: ["POST"] },
        "transactions.show": {
            uri: "transactions/{transaction}",
            methods: ["GET", "HEAD"],
            parameters: ["transaction"],
            bindings: { transaction: "id" },
        },
        "transactions.edit": {
            uri: "transactions/{transaction}/edit",
            methods: ["GET", "HEAD"],
            parameters: ["transaction"],
            bindings: { transaction: "id" },
        },
        "transactions.update": {
            uri: "transactions/{transaction}",
            methods: ["PUT", "PATCH"],
            parameters: ["transaction"],
            bindings: { transaction: "id" },
        },
        "transactions.destroy": {
            uri: "transactions/{transaction}",
            methods: ["DELETE"],
            parameters: ["transaction"],
            bindings: { transaction: "id" },
        },
        "transactions.update-status": {
            uri: "transactions/{transaction}/update-status",
            methods: ["POST"],
            parameters: ["transaction"],
            bindings: { transaction: "id" },
        },
        "seller-requests.index": {
            uri: "seller-requests",
            methods: ["GET", "HEAD"],
        },
        "seller-requests.show": {
            uri: "seller-requests/{seller_request}",
            methods: ["GET", "HEAD"],
            parameters: ["seller_request"],
        },
        "seller-requests.edit": {
            uri: "seller-requests/{seller_request}/edit",
            methods: ["GET", "HEAD"],
            parameters: ["seller_request"],
        },
        "seller-requests.update": {
            uri: "seller-requests/{seller_request}",
            methods: ["PUT", "PATCH"],
            parameters: ["seller_request"],
        },
        "seller-requests.destroy": {
            uri: "seller-requests/{seller_request}",
            methods: ["DELETE"],
            parameters: ["seller_request"],
        },
        "seller-requests.update-status": {
            uri: "seller-requests/{sellerRequest}/update-status",
            methods: ["POST"],
            parameters: ["sellerRequest"],
            bindings: { sellerRequest: "id" },
        },
        "seller-requests.convert-to-property": {
            uri: "seller-requests/{sellerRequest}/convert-to-property",
            methods: ["POST"],
            parameters: ["sellerRequest"],
            bindings: { sellerRequest: "id" },
        },
        "password.request": {
            uri: "forgot-password",
            methods: ["GET", "HEAD"],
        },
        "password.email": { uri: "forgot-password", methods: ["POST"] },
        "password.reset": {
            uri: "reset-password/{token}",
            methods: ["GET", "HEAD"],
            parameters: ["token"],
        },
        "password.store": { uri: "reset-password", methods: ["POST"] },
        "verification.notice": {
            uri: "verify-email",
            methods: ["GET", "HEAD"],
        },
        "verification.verify": {
            uri: "verify-email/{id}/{hash}",
            methods: ["GET", "HEAD"],
            parameters: ["id", "hash"],
        },
        "verification.send": {
            uri: "email/verification-notification",
            methods: ["POST"],
        },
        "password.confirm": {
            uri: "confirm-password",
            methods: ["GET", "HEAD"],
        },
        "password.update": { uri: "password", methods: ["PUT"] },
        "storage.local": {
            uri: "storage/{path}",
            methods: ["GET", "HEAD"],
            wheres: { path: ".*" },
            parameters: ["path"],
        },
    },
};
if (typeof window !== "undefined" && typeof window.Ziggy !== "undefined") {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
